### ISSUE TITLE
The button navigate to null page as shown in attatchment

### ISSUE THREAD

**Issue by sheikhjebran** [rveachkc/pymsteams#102]
**Describe the bug**
The LinkButton navigate me to null page

**To Reproduce**
#### CODE below ######
my_teams_message = pymsteams.connectorcard(webhook_url)
my_teams_message.addLinkButton("JenkinsJob", pyutilityconfig.BUILD_URL)
my_teams_message.send()

**Expected behavior**
when the URL is " http://www.google.com it works , but when the i use my Jenkins-URL then it navigate to null 

**Screenshots**
<img width="1789" alt="Screenshot 2021-07-11 at 10 26 34 PM" src="https://user-images.githubusercontent.com/18025358/125203690-1e3a2c00-e297-11eb-8010-9ecaf159eb48.png">

**Additional context**
The button works fine for "http://www.google.com" but it dont work for my jenkins URL

**Comment by rveachkc** [comment]
This is going to be a problem with how Microsoft handles the url, not something that can be corrected on the pymsteams side.
