### ISSUE TITLE
Is it possible to get a reply from the channel, or the result of an action back?

### ISSUE THREAD

**Issue by esmedwards** [rveachkc/pymsteams#104]
Sending messages is straightforward. But is it possible to receive replies back. 
For example if I post a yes or no `multiple choice` action, is there a way to get what the user selected on the other end?

**Comment by rveachkc** [comment]
Closing the loop on this.  This library has no way of returning the status of this multiple choice button.  (Thanks @Dritzii  for the initial response).

There are a couple out of scope methods that I can think of for this:

- set up a separate web api server to catch api calls from potential actions
- Use another library to create a bot, as described here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots
