### ISSUE TITLE
Non-http link buttons don't show

### ISSUE THREAD

**Issue by donquibeats** [rveachkc/pymsteams#108]
Thanks for making a really handy library for posting updates to Teams.

I'm using the addLinkButton() call with the button text and a URL.

I'm finding that if I use a http:// URL, it works fine: `.addLinkButton("Google it", "http://www.google.com/")`

However when I try to use a URL that's a local protocol supported on our company network, Teams doesn't show the button. `.addLinkButton("Open link", "localsystem://id432")` _doesn't_ work.

I can't find anything in the Webhook API to either confirm or deny whether this is a Teams thing and it simply doesn't support custom protocol URL's, or whether there's something I could do differently in pymsteams in order to make a local button show?

Thanks

**Comment by rveachkc** [comment]
Teams requires a public url.  See https://github.com/rveachkc/pymsteams/issues/106#issuecomment-905710803 on #106 for more info.

**Comment by donquibeats** [comment]
Thanks for confirming
