### ISSUE TITLE
[Question] Delete message generator by Incoming Webhook

### ISSUE THREAD

**Issue by quyvsquy** [rveachkc/pymsteams#115]
Hi, thank you for creating an interesting repo to format messages and post to Microsoft Teams. 
But, I have a question, how can I delete a conversation when call send() method?
Thank you,

**Comment by rveachkc** [comment]
I'm not entirely sure what you are asking about.

In the event you are wanting to delete a message from appearing in a teams chat - apologies, but that is not supported.

If you wanting to delete the teams connector card object from memory, you would need to delete the object:

```python
myTeamsMessage = pymsteams.async_connectorcard("<Microsoft Webhook URL>")
myTeamsMessage.text("This is my message")
del myTeamsMessage
```
