### ISSUE TITLE
Add tags to connectorcard

### ISSUE THREAD

**Issue by stefanbie** [rveachkc/pymsteams#120]
Hi! 
I have tried to tag people and groups using connectorcard like this

```
webhook = "xxx"
myTeamsMessage = pymsteams.connectorcard(webhook)
msg = "Hello @Someone123"
myTeamsMessage.text(msg)
myTeamsMessage.send()
```
...but it does not seems to be working. Can this be achieved in some other way or else, could it be implemented?
Thanks!

**Comment by rveachkc** [comment]
This is not supported by the connectorcard api.

**Comment by stefanbie** [comment]
Hi @rveachkc It should be supported according to
https://docs.microsoft.com/en-us/answers/questions/616853/notifying-users-on-teams-channel-using-adaptive-ca.html

**Comment by rveachkc** [comment]
1 - that's not the api this library uses
2 - this is a duplicate issue. There are others discussing this, and even a PR for it.

**Comment by stefanbie** [comment]
Thanks @rveachkc, yould you please provide a link for that? :)

**Comment by YugoHino** [comment]
I think the link is here
https://github.com/rveachkc/pymsteams/issues/11

**Comment by stefanbie** [comment]
Thanks!
