### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by nouni19** [rveachkc/pymsteams#121]
How do I take input from MS teams? There isn't anything about it in the docs
By taking input I mean: if someone wrote "!1+1"(example), python can put it in a variable of some sort

I found it in the docs but it wasn't that clear on how to retrieve the value

**Comment by nouni19** [comment]
I found it but it is still pretty unclear how I retrieve the value

**Comment by rveachkc** [comment]
The purpose of this library is to send webhooks to post messages.  The webhook api does not support reading of messages.

To read input, you're going to want to create a bot, which would be out of scope.
