### ISSUE TITLE
TeamsWebhookException despite successful POST

### ISSUE THREAD

**Issue by alextadams88** [rveachkc/pymsteams#135]
**Describe the bug**
During `send()`, Teams returns a successful response payload, and the message successfully appears in the teams channel, however a `TeamsWebhookException` is raised regardless. 

pymsteams is expecting the response text to simply be "1"
```
if r.status_code == requests.codes.ok and r.text == '1': # pylint: disable=no-member
            return True
        else:
            raise TeamsWebhookException(r.text)
```    
However r.text is actually:

```
{"version":"1.1","content":{"headers":[{"key":"Content-Type","value":["text/plain; charset=utf-8"]}]},"statusCode":200,"reasonPhrase":"OK","headers":[],"trailingHeaders":[],"requestMessage":null,"isSuccessStatusCode":true}
```

**To Reproduce**

Send any message. It may be dependent on the webhook you are hitting. 

**Expected behavior**
TeamsWebhookException is not thrown. 

**Screenshots**
![thrownException](https://user-images.githubusercontent.com/28212242/193682769-3caedeb6-26d7-4b70-b301-2868bc31f923.png)
![successfulTeamsMessage](https://user-images.githubusercontent.com/28212242/193682835-fb44f4e7-befc-4b53-9873-4c49ead80375.png)

**Additional context**
This was working for us up until Friday, 9/30, around 19:00, when it suddenly started failing. Seems that perhaps Teams may have changed their API.

**Comment by alextadams88** [comment]
after removing the check for `r.text == '1'`, it was successful.

![demonstratingTheChange](https://user-images.githubusercontent.com/28212242/193683585-26aba7b9-68bd-48f5-be9d-dfb3d6ee1f56.png)

![anotherSuccessfulTeamsMessage](https://user-images.githubusercontent.com/28212242/193683608-983aa36e-6114-478e-841b-9d719db47bec.png)

**Comment by alextadams88** [comment]
I attempted to create a pull request to address this change, but I received 403 when trying to push a new branch. So I cannot create PR.

**Comment by kingsleyadam** [comment]
We're getting the same and noticed the same behavior. It's true, if the response code is successful, then it can be assumed the message was successfully sent (although maybe there was a reason at the time that the text response also needed to be 1).

Unfortunately I can't find any documentation on the api itself and the possible responses. https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL. Maybe I'm just missing it.

Until this is patched I'm going to implement another catch downstream to verify the response.

**Comment by rveachkc** [comment]
Thanks, I noticed the "1" was passed, even though it was never documented.  This was done out of an abundance of caution.

Thanks to @alextadams88, it was trivial to merge the PR and release in [v0.2.2](https://github.com/rveachkc/pymsteams/releases/tag/0.2.2)

**Comment by atc0005** [comment]
For anyone else coming across this regarding the response code needing to be `1`, see also:

- https://github.com/rveachkc/pymsteams/issues/75

FWIW, I'm still seeing a `1` as the response code from submitting via webhook URL. Perhaps they're rolling out the change to specific tenants first before deploying the change for everyone?

**Comment by mockodin** [comment]
> We're getting the same and noticed the same behavior. It's true, if the response code is successful, then it can be assumed the message was successfully sent (although maybe there was a reason at the time that the text response also needed to be 1).
> 
> Unfortunately I can't find any documentation on the api itself and the possible responses. https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL. Maybe I'm just missing it.
> 
> Until this is patched I'm going to implement another catch downstream to verify the response.
> 
> For anyone else that may need this in the meantime.
> 
> ```python
> # Patch in a successful response, see: https://github.com/rveachkc/pymsteams/issues/135
> try:
>     card.send()
> except pymsteams.TeamsWebhookException as teams_exception:
>     try:
>         # If this is a successful response it should return a JSON value.
>         # If it's not successful it could return a number of things, catch this.
>         _response = json.loads(teams_exception.args[0])
>     except ValueError:
>         raise teams_exception
> 
>     if _response.get('statusCode') != 200:
>         raise teams_exception
> ```

Worth noting that originally MS always returned 200 even when there was an internal failure, you had to check the body for "1", the appears to have changed. Oddly I see documentation of the change as early as 2019 however it only just now broke.
