### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by pasket** [rveachkc/pymsteams#14]
My Internet connection must be through proxy. Is it possible to configure the proxy server to establish the connection to the webhook?
Thanks.

**Comment by rveachkc** [comment]
I use the requests library for all http calls.

Looking at the documentation, one can be configured using environment variables.
http://docs.python-requests.org/en/master/user/advanced/#proxies

I wouldn't be opposed to adding it to the code, as it seems pretty straight forward, but can you test with this first?

**Comment by pasket** [comment]
Yes, it works. 

As you said it also works doing a post with requests library. It would be great adding to the code.

```
webhook_url = https://...
proxies = {'http': 'http://user:pass@10.10.1.10:3128/'}
json_payload = {'text': "Hello"}
requests.post(<webhook_url>, proxies=<proxies>, json=json_payload>)
```


Thanks!

**Comment by rveachkc** [comment]
I don't have a proxy ready to  test with this.  Would you be willing to try a branch?

```bash
pip install --upgrade https://github.com/rveachkc/pymsteams/archive/14-proxy-request.tar.gz
```

If you need a socks5 proxy, you will need to run this too:

```bash
pip install --upgrade requests[socks]
```

The proxy definition is set in the class init.  The proxy specified should match what is shown in the requests documentation: http://docs.python-requests.org/en/master/user/advanced/#proxies
Examples:

* `http://10.10.1.10:3128`
* `http://10.10.1.10:1080`
* `http://user:pass@10.10.1.10:3128/`
* `socks5://user:pass@host:port`

Example code:

```python
import pymsteams

# Create card with proxy defined:
myTeamsMessage = pymsteams.connectorcard(
    "<Microsoft Webhook URL>",
    http_proxy="http://10.10.1.10:3128",
    https_proxy="http://10.10.1.10:1080"
)

### then, the rest is the same.

# Add text to the message.
myTeamsMessage.text("this is my text")

# send the message.
myTeamsMessage.send()
```

**Comment by hostadmin** [comment]
Hi,

I tested in with http/https proxies and it's working fine
Could you please tell when you plan to merge it to master?

Thank you in advance!

**Comment by rveachkc** [comment]
I merged it into master.  I'll work on the pypi upload later.  (I should really automate this)

**Comment by rveachkc** [comment]
Updated on PyPi - Uploads are now automated using CircleCI
