### ISSUE TITLE
  // , What if I just want to send a simple, plain text message to a user via the API? 

### ISSUE THREAD

**Issue by v6** [rveachkc/pymsteams#15]
// , This seems more geared toward automation of adaptive cards, not simple message automation.

**Comment by rveachkc** [comment]
Sorry for the delay.
Correct, my use is to automate messaging via teams, and I reference this functionality from other tasks.

The card api can be used to make something as simple or as complex as you'd like.  In my testing, I found that only the text is required to send a simple message: https://github.com/rveachkc/pymsteams#creating-connectorcard-messages
Anything else is just a bonus.
