### ISSUE TITLE
Retirement of office 365 connectors - implications to this library

### ISSUE THREAD

**Issue by mm225022** [rveachkc/pymsteams#156]
Microsoft announced that they are [retiring O365 connectors](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/)

This will obviously impact the functionality of this library as it works via connectors.

Is there any plan to update the library to be able to continue its functionality once Microsoft deprecates the connectors?

**Comment by rveachkc** [comment]
Duplicate, see #155
