### ISSUE TITLE
Add Python 2 Support

### ISSUE THREAD

**Issue by ALERTua** [rveachkc/pymsteams#24]
"pip install pymsteams" installs version 0.1.3 :
`
Successfully installed pymsteams-0.1.3
`

"pip install pymsteams==0.1.7" fails
`
Collecting pymsteams==0.1.7
  Could not find a version that satisfies the requirement pymsteams==0.1.7 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3)
No matching distribution found for pymsteams==0.1.7
`

**Comment by rveachkc** [comment]
What version of python and pip were you using?

I just tried to reproduce the error in a Windows Python 3.6.5 venv with pip 9.0.3 and pip 18.1 with no issues:
```
(testvenv) λ pip install pymsteams==0.1.7
Collecting pymsteams==0.1.7
Collecting requests==2.20.0 (from pymsteams==0.1.7)
  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\rv019415\documents\venvs\testvenv\lib\site-packages (from requests==2.20.0->pymsteams==0.1.7) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rv019415\documents\venvs\testvenv\lib\site-packages (from requests==2.20.0->pymsteams==0.1.7) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\rv019415\documents\venvs\testvenv\lib\site-packages (from requests==2.20.0->pymsteams==0.1.7) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\rv019415\documents\venvs\testvenv\lib\site-packages (from requests==2.20.0->pymsteams==0.1.7) (3.0.4)
Installing collected packages: requests, pymsteams
Successfully installed pymsteams-0.1.7 requests-2.20.0

(testvenv) λ pip freeze
certifi==2018.11.29
chardet==3.0.4
idna==2.7
pymsteams==0.1.7
requests==2.20.0
urllib3==1.24.1
```

Then, I kicked off a Docker build based on the Official [Python 3.7 Debian slim stretch image](https://hub.docker.com/_/python/), which also installed the module successfully.

**Comment by ALERTua** [comment]
Python 2.7.15
pip 18.1

**Comment by rveachkc** [comment]
This module is currently for Python 3 only.

If you need Python 2 support, I'd happily review pull requests against the develop branch.  I just can't justify the time I would need to spend on doing this myself.

In my testing, I did find an issue where pymsteams was specifying a specific version of requests vs allowing a greater than or equal to match.
Error:
```
pymsteams 0.1.7 has requirement requests==2.20.0, but you'll have requests 2.20.1 which is incompatible.
```

I went ahead and pushed v 0.1.8 with this small change to the [setup.py](https://github.com/rveachkc/pymsteams/commit/a6d87ca27fbdfd8fa7951ad087829af0631fd7f5).

**Comment by ALERTua** [comment]
I got some results:
I pulled the development branch.
Changed `python_requires='>=2.7.15'`
`pip install pymsteams` from the local path.
And everything works :)

**Comment by rveachkc** [comment]
Ahh, I forgot about that. I changed up the setup.py when I added my CircleCI automation stuff.

I've changed it to `python_requires='>=2.7'` for version 0.1.9, which is currently in develop.  I'll try to validate and push to pypi today, but feel free to install from develop and do your own testing for now:

```bash
pip install --upgrade https://github.com/rveachkc/pymsteams/archive/develop.tar.gz
```

**Comment by rveachkc** [comment]
Python 2.7 support was added back to version 0.1.9, which was just uploaded to PyPI.
