### ISSUE TITLE
Validate message was received

### ISSUE THREAD

**Issue by jeff-shep** [rveachkc/pymsteams#33]
Is there a way to check the response from the .send call to check that the message was posted into Teams without having to manually check?

**Comment by rveachkc** [comment]
The send method checks the http status code and return a Boolean value representing the success of the http call.

This webhook wrapper is pretty simple and needs to rely on the http code to determine if a message was accepted or not.

Would it be better to raise an exception instead?

https://github.com/rveachkc/pymsteams/blob/master/pymsteams/__init__.py#L130

**Comment by martinthurn** [comment]
YES please raise an exception!  The send() method can also fail if the message is malformed; the caller needs to know what went wrong with as much detail as possible.

**Comment by rveachkc** [comment]
The `TeamsWebhookException` exception will now be raised added in #43 and [version 0.1.11](https://github.com/rveachkc/pymsteams/releases/tag/0.1.11).
This was also auto-updated [PYPI](https://pypi.org/project/pymsteams/0.1.11/).
