### ISSUE TITLE
Potential Actions

### ISSUE THREAD

**Issue by Seonin** [rveachkc/pymsteams#36]
If pull request was approved, please add this code example to the read me 

`myTeamsPotentialAction1 = pymsteams.potentialaction(_name = "Add a comment")
myTeamsPotentialAction1.addInput("TextInput","comment","Add a comment here",False)
myTeamsPotentialAction1.addAction("HttpPost","Add Comment","http://...")

myTeamsPotentialAction2 = pymsteams.potentialaction(_name = "Set due date")
myTeamsPotentialAction2.addInput("DateInput","dueDate","Enter due date")
myTeamsPotentialAction2.addAction("HttpPost","save","https://...")

myTeamsPotentialAction3 = pymsteams.potentialaction(_name = "Change Status")
choices  = [
    {
        "display": "In progress",
        "value": "1"
    },
    {
        "display": "Active",
        "value": "2"
    },
    {
        "display": "Closed",
        "value": "3"
    }]
myTeamsPotentialAction3.addInput("MultichoiceInput","list","Select a status",False,choices)
myTeamsPotentialAction3.addAction("HttpPost","Save","http://...")

myTeamsMessage.addPotentialAction(myTeamsPotentialAction1)
myTeamsMessage.addPotentialAction(myTeamsPotentialAction2)
myTeamsMessage.addPotentialAction(myTeamsPotentialAction3)

myTeamsMessage.summary("Test Message")

myTeamsMessage.send()`

**Comment by rveachkc** [comment]
@Seonin , would you be able to update the readme with your pull request?

**Comment by rveachkc** [comment]
Thanks for the contribution.
This has been released in [0.1.10](https://github.com/rveachkc/pymsteams/releases/tag/0.1.10)
