### ISSUE TITLE
Enhancement Request - HTML Body

### ISSUE THREAD

**Issue by McKlayne** [rveachkc/pymsteams#41]
It would be really nice to display information in a message/channel card via html. This would allow users to display customized data frames and other information.

**Comment by rveachkc** [comment]
Unfortunately, we're at the mercy of the Teams API.  It does not appear that they have support for this.

There is quite a bit of styling that can be done to the message: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#card-examples
