### ISSUE TITLE
HttpPOST action body parameter ?

### ISSUE THREAD

**Issue by jjh74** [rveachkc/pymsteams#44]
Hello,

I can't find a way to add "body" parameter to (HttpPOST) potential actions (https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#httppost-action).
I made a small patch for this (https://github.com/jjh74/pymsteams/tree/action_body) if this seems reasonable I can create a PR for this.
(Perhaps "headers" and "bodyContentType" should/could be exposed, but for my purposes "body" is enough).

**Comment by rveachkc** [comment]
Would you mind making a pull request with both changes into the develop branch?

It would be easiest for me to review if each change were it's own commit if possible.

**Comment by jjh74** [comment]
Thanks, I'll create a PR with separate commits. It'll be couple of days before I'll have time to do this. I'll close these issues for now.
