### ISSUE TITLE
Potentialaction w/out input/actions ?

### ISSUE THREAD

**Issue by jjh74** [rveachkc/pymsteams#45]
Hello,
I can't find a way to add a potentialaction without actions: [] array. I'd need to add something like this:
```json
    {
      "@type": "HttpPOST",
      "name": "Click Me",
      "target": "https://...",
      "body": "{'a': 'b'}"
    }
```
(https://messagecardplayground.azurewebsites.net/ and "Github issue opened sample"). This adds a button you can just click and teams does POST straight away (without displaying any additional buttons/inputs).

I made a patch that adds addRawPotentialAction function for this (https://github.com/jjh74/pymsteams/tree/raw_potentialaction2) if this looks reasonable/acceptable I can create a PR for this.

**Comment by rveachkc** [comment]
I can review. Can you make a pull request into the develop branch?

**Comment by jjh74** [comment]
I'll make a PR later.
