### ISSUE TITLE
Feature Request: File upload/attachment support

### ISSUE THREAD

**Issue by docdawning** [rveachkc/pymsteams#53]
Please add support to use Teams' Attach File feature. This would be extremely helpful for my use case, the lack of it in pymsteams is causing me to look at switching to another solution. Thank you for pymsteams, however, it is very clean.

**Comment by rveachkc** [comment]
I've looked at doing this before, but have been unable to find a way to do this using the existing API: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

Are you aware of a way to do this, or a different project that does the same?

**Comment by CaseGuide** [comment]
Also wish this was available with this library

**Comment by rveachkc** [comment]
This feature is not supported by the webhook API.  If you need this functionality, you may need to create a full blown teams application.
