### ISSUE TITLE
Message not fully displayed 

### ISSUE THREAD

**Issue by RonZhang724** [rveachkc/pymsteams#60]
**Describe the bug**
I have a message with 20+ sections, and after sending the message to the teams, the message is collapsed. After clicking see more, only 10 of the sections are displayed. I am working on the macOS version of the teams. 

The message gets fully displayed on the iOS though

**Comment by hmoffatt** [comment]
If the iOS client displays it and the macOS doesn't, that sounds like a client bug, not a pymsteams bug?

**Comment by rveachkc** [comment]
Thanks for the initial reply @hmoffatt, I agree.

From the MS Teams documentation (https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#notes-on-the-office-365-connector-card):

> Each Connector card can display a maximum of 10 sections, and each section can contain a maximum of 5 images and 5 actions.
> Any additional sections, images, or actions in a message will not appear.
