### ISSUE TITLE
Can't POST to webhook if too many characters

### ISSUE THREAD

**Issue by AugustasV** [rveachkc/pymsteams#64]
**Describe the bug**
Can't send webhook if it's too many characters in it.

**To Reproduce**
Try to send ALOT of characters

**Expected behavior**
Expected to send information to my chanell using webhook. But it just do nothing. All works when using command myTeamsMessage.printme()
Everything works then sending couple of lines.

**Comment by rveachkc** [comment]
There is nothing within the library that would limit the length of your message.  This is likely a limitation with the Microsoft API.
