### ISSUE TITLE
How to create show/hide text in the message body

### ISSUE THREAD

**Issue by grayaii** [rveachkc/pymsteams#77]
I see that pager duty creates messages that have collapsable text, like this:
Before:
![before_click](https://user-images.githubusercontent.com/847072/92059308-e1400780-ed5e-11ea-8526-e02dab1706b5.jpg)

After:
![after_click](https://user-images.githubusercontent.com/847072/92059323-eac96f80-ed5e-11ea-954d-6216f4458649.jpg)

Is this functionality possible with pymstreams?
Thanks!

**Comment by grayaii** [comment]
I should have mentioned that I think it's called a "container":
https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card

No idea if that helps or not.

**Comment by rveachkc** [comment]
pymsteams uses a much simpler api, which restricts formatting to options available in the MessageCard document: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference
I don't see any reference to containers in that document.

I would be open to updating the library to send Adaptive cards as well, I just don't have a ton of time to update it.  Pull Requests are always welcome.
