### ISSUE TITLE
How to attach a file that can be downloaded?

### ISSUE THREAD

**Issue by mahima2112** [rveachkc/pymsteams#81]
Can I attach a csv file to Teams message? If not, is it possible to generate a link using python script for box and pass it in download button from where it can be downloaded?

**Comment by rveachkc** [comment]
The api used by pymsteams does not support file attachments.  If you want to add a download link, the best path would be to add your own url through an OpenURI action: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#openuri-action
