### ISSUE TITLE
Make send method async-able

### ISSUE THREAD

**Issue by gui-don** [rveachkc/pymsteams#84]
Hello,

I would like to connect send multiple messages, possibly to multiple Teams.
Is it possible to offer an alternative async `send`?

**Comment by rveachkc** [comment]
This has already been discussed in https://github.com/rveachkc/pymsteams/issues/71, so I'm going to mark as duplicate and close.

Async is currently a bit out of scope of this library, but I wouldn't be opposed to adding it.  Pull request welcome.  I think it's definitely been long enough that I'm ok with dropping python 2 support at this point.
