### ISSUE TITLE
HttpPost request from Teams on pymsteams.potentialaction is empty

### ISSUE THREAD

**Issue by tillsteinbach** [rveachkc/pymsteams#89]
When executing the Potential Action from MS teams the request does not contain any content in the POST (content-length 0)

**Comment by rveachkc** [comment]
There's not enough information here to help. Can you provide more
information, like the code you are using to generate the message and the
output of the connector card using printer?
https://github.com/rveachkc/pymsteams/blob/master/pymsteams/__init__.py#L202

**Comment by tillsteinbach** [comment]
I have to provide a minimum sample, but for now I think the problem is that the body is empty. it is missing something like "id={{id.value}}" or an equivalent in json. If the Idea is that the body should be provided by the action itself it would make sense to make that an argument to addPotentialAction.

**Comment by rveachkc** [comment]
I was waiting on input for this, but I suspect it was resolved by !103.
