### ISSUE TITLE
Is it possible to post to specific Channels?

### ISSUE THREAD

**Issue by kentgeorgeson** [rveachkc/pymsteams#9]
Have this working, awesome work thank you.   Is it possible though to post to channels within a Team?   Currently it just goes to the group in Outlook.   Was hoping to get a message into a specific channel within a group

**Comment by rveachkc** [comment]
From the API Documentation, webhooks are created for individual channels.  If you want to post to multiple channels, you could define multiple classes with different webhook names.
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors

If this is a requirement, you could explore developing a teams bot, but that is beyond the scope of what I was attempting to do with this code.

**Comment by rveachkc** [comment]
This is not something that can be done using webhooks now, but I'll keep it open in the event the API is ever updated.
