### ISSUE TITLE
Every time a new message is sent, another button gets added to the message.

### ISSUE THREAD

**Issue by cschreiberBES** [rveachkc/pymsteams#92]
Hello, 

I have a function that sends a message to a  MS Teams channel every time it is called. The first call, the message sends correctly and only contains 1 button. Every time the function is called after that, another button gets added to the message.

My Function:
```python
def sendToMSTeams (speed, name, driveTime, distance, scName):
    title = 'Driver ETA Alert - {0} Minutes from {1} Processing Center'.format(driveTime, scName)
    text = '{0} is {1} miles away from the {2} processing center. They will arrive in {3} Minutes. They are currently traveling at {4} MPH.'.format(name , str(distance), scName, str(driveTime), str(speed))
    btnText = "View on Map"
    btnURL = "https://www.google.com/"
    msTeamsConnection.title(title)
    msTeamsConnection.text(text)
    msTeamsConnection.addLinkButton(btnText, btnURL)
    msTeamsConnection.send()
```

**Expected behavior**
I expect that, for every message sent, only one button displays on the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/65367906/114222167-39b23580-993c-11eb-92ae-f996f5202e83.png)

Please let me know if this is a genuine bug, or I am just missing something.

Thank you!

**Comment by cschreiberBES** [comment]
`def sendToMSTeams (speed, name, driveTime, distance, scName):
    title = 'Driver ETA Alert - {0} Minutes from {1} Processing Center'.format("7", scName)
    text = '{0} is {1} miles away from the {2} processing center. They will arrive in {3} Minutes. They are currently traveling at {4} MPH.'.format(name , str(distance), scName, str(driveTime), str(speed))
    btnText = "View on Map"
    btnURL = "https://bentear.maps.arcgis.com/home/webmap/viewer.html?webmap=1a0c024868a44abb840e38e988404746"
    msTeamsConnection.title(title)
    msTeamsConnection.text(text)
    msTeamsConnection.addLinkButton(btnText, btnURL)
    msTeamsConnection.send()`

**Comment by rveachkc** [comment]
This happens because the entire message persists, including the text, title, buttons, etc.

The addLinkButton appends a new button instead of replacing it.

You don't see the same behavior with the other elements, because they are simply overwritten.

The connector card object represents a message, not a connection.

**Comment by cschreiberBES** [comment]
Thanks @rveachkc for the help! I will give that a try.
