### ISSUE TITLE
Picture with text on the side

### ISSUE THREAD

**Issue by betuxy** [rveachkc/pymsteams#99]
Is it possible to get some text (video description) right to the picture like shown below? 

Here's the code I used
```python
    myTeamsMessage = pymsteams.connectorcard(teams_hook)
    myTeamsMessage.title(str(message["channel_name"]) + ": " + str(message["title"]))
    myTeamsMessage.text(" ")
    myMessageSection = pymsteams.cardsection()
    myMessageSection.addImage(message["thumb_nail"])
    myMessageSection.text(message["channel_info"])
    myMessageSection.linkButton("Click to Watch!", message["link"])
    myTeamsMessage.addSection(myMessageSection)
    myTeamsMessage.send()
```

<a href="https://imgur.com/Vt4Xh34"><img src="https://i.imgur.com/Vt4Xh34.png" title="source: imgur.com" /></a>

**Comment by rveachkc** [comment]
I do not believe this is supported by the version of the api that this library uses.  Feel free to double check me: https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference
